"""Load config.yaml and resolve relative paths against the project root."""

from __future__ import annotations

from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG = PROJECT_ROOT / "config.yaml"


def load_config(path: str | Path | None = None) -> dict:
    cfg_path = Path(path) if path else DEFAULT_CONFIG
    if not cfg_path.exists():
        raise FileNotFoundError(f"No config file at {cfg_path}")
    with cfg_path.open(encoding="utf-8") as fh:
        config = yaml.safe_load(fh) or {}

    config["_root"] = str(PROJECT_ROOT)
    config["keywords"] = _load_keywords(config)
    config.setdefault("database", {})
    config["database"]["path"] = str(resolve(config["database"].get("path", "data/tenders.sqlite3")))
    out = config.setdefault("output", {})
    out["csv_path"] = str(resolve(out.get("csv_path", "out/shortlist.csv")))
    out["html_path"] = str(resolve(out.get("html_path", "out/shortlist.html")))
    out["json_path"] = str(resolve(out.get("json_path", "site/data.json")))

    inbox = (config.get("sources") or {}).get("csv_inbox")
    if inbox:
        inbox["folder"] = str(resolve(inbox.get("folder", "inbox")))
    return config


def _load_keywords(config: dict) -> dict:
    """Resolve the keyword taxonomy.

    `keywords_file` (generated by tools/import_keywords.py) is the base.
    `keywords_extra` in config.yaml is merged on top, so you can add a term
    without regenerating the file: groups are matched by name and their terms
    appended, negative terms are appended, CPV boosts are overwritten by key.
    An inline `keywords` block still works if you'd rather not use a file.
    """
    base = dict(config.get("keywords") or {})
    kw_file = config.get("keywords_file")
    if kw_file:
        path = resolve(kw_file)
        if not path.exists():
            raise FileNotFoundError(
                f"keywords_file points at {path}, which does not exist. "
                "Run: python tools/import_keywords.py")
        with path.open(encoding="utf-8") as fh:
            base = yaml.safe_load(fh) or {}

    extra = config.get("keywords_extra") or {}
    if not extra:
        return base

    groups = {g["name"]: g for g in base.get("groups", [])}
    for g in extra.get("groups", []):
        name = g.get("name")
        if name in groups:
            groups[name]["terms"] = list(groups[name].get("terms", [])) + list(g.get("terms", []))
            if "weight" in g:
                groups[name]["weight"] = g["weight"]
        else:
            groups[name] = g
    base["groups"] = list(groups.values())

    if extra.get("negative", {}).get("terms"):
        neg = base.setdefault("negative", {"weight": -7.0, "terms": []})
        neg["terms"] = list(neg.get("terms", [])) + list(extra["negative"]["terms"])
        if "weight" in extra["negative"]:
            neg["weight"] = extra["negative"]["weight"]

    if extra.get("cpv_boost"):
        base.setdefault("cpv_boost", {}).update(extra["cpv_boost"])
    return base


def resolve(path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else PROJECT_ROOT / p
